//HANDLING OF ENVIRONMENT VARIABLES
const VITE_API_URL = import.meta.env.VITE_API_URL;
const NEXT_PUBLIC_GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;

export { VITE_API_URL, NEXT_PUBLIC_GOOGLE_CLIENT_ID };