//HANDLING OF ENVIRONMENT VARIABLES
const NEXT_PUBLIC_API_URL = import.meta.env.VITE_API_URL;
const NEXT_PUBLIC_GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;

export { NEXT_PUBLIC_API_URL, NEXT_PUBLIC_GOOGLE_CLIENT_ID };